// This is an autogenerated file -- DO NOT EDIT

import {DataSourceConstructor} from '@loopback/repository';
const dsConfig = require('qa.datasource.json');

export class QaDataSourceBase extends DataSourceConstructor {
  constructor() {
    super(dsConfig);
  }
}
